### ISSUE TITLE
Change NPC Tshirt Color

### ISSUE THREAD

**Issue by HerleX** [AndreasWebdev/Carniwell#15]
Let the NPC Tshirt color react to it's happiness

**Comment by Sashify** [comment]
Other spawning NPCs are resetting the colors of the material. 

Testing it with only 1 NPC in scene it works. As soon as other NPCs are spawn. The material gets a "reset".

Changing the color of the material on one NPC, is a global change on the material.
@HerleX

**Comment by AndreasWebdev** [comment]
Maybe generate a material programmatically?

**Comment by Sashify** [comment]
http://thomasmountainborn.com/2016/05/25/materialpropertyblocks/

**Comment by Sashify** [comment]
Working on it.

**Comment by Sashify** [comment]
228490b4b2a0f0219888c2a3d1126b448a13aa51
